language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-text
