language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

jobs:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-text
