name: PR - Linter
on: pull_request
jobs:
  test:
    name: PHP ${{ matrix.php }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phplint, phpcs, cs2pr
      - name: Tool versions
        run: |
          php --version
          phplint --version
          phpcs --version
      - name: Run PHP Linter
        run: phplint
      - name: Run PHP CodeSniffer
        continue-on-error: true
        run: phpcs -p --encoding=utf-8 -s -p --report-full --report-checkstyle=./phpcs-report.xml
      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml
